### ISSUE TITLE
[Bug] Cannot type anything in search box

### ISSUE THREAD

**Issue by boom210232** [ThaiRepose/thairepose#87]
## Step to reproduce       
1. login with any option (OAuth via google or normal register id)
2. type something

## Expected result
Can type anything for searching 

## Actual result 
Cannot type anything. After typing for a few letters search bar will block with the "!" icon. 

## screen shot           
![ThaiRepose - Google Chrome 11_23_2021 1_49_54 PM](https://user-images.githubusercontent.com/73125941/142981517-a3f52bd0-fe42-4fe3-b720-00e84d477711.png)

**Comment by pontakornth** [comment]
For maintainers, the API key is expired.

**Comment by boom210232** [comment]
@pontakornth Thanks for adding more detail to this problem.

**Comment by vitvara** [comment]
> For maintainers, the API key is expired.

Thank you for your answer.
Now we deactivate our google map API-key because we have trouble that we use the same frontend and backend API-key but google won't let us set two application restrictions per key.

@boom210232 
Thank you for your questions.
We are working on this issue, The site will be fully finished by Friday.

**Comment by vitvara** [comment]
And about the OAuth, we are changing the redirect URL from localhost to the domain name also this feature will be available by Friday.

**Comment by tboonma** [comment]
Not a defect, it's in process of configuration. Fixed with api key restriction, the site is able to use now.
